export class BrainView{
 constructor(canvas,neurons,edges,onSelect){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.neurons=neurons;this.edges=edges;this.onSelect=onSelect;this.rotation=[-.18,.28];this.zoom=1;this.pan=[0,0];this.selected=0;this.active=new Set();this.silent=new Set();this.firing=new Set();this.path=[];this.connections=false;this.filtered=new Set(neurons.map((_,i)=>i));this.projected=[];this.dragged=false;this.pointer=new Map();this.positions=this.normalize();this.bind();this.resize();new ResizeObserver(()=>this.resize()).observe(canvas);this.draw()}
 normalize(){const points=this.neurons.map(n=>n.position||[0,0,0]);let lo=[0,1,2].map(j=>Math.min(...points.map(p=>p[j]))),hi=[0,1,2].map(j=>Math.max(...points.map(p=>p[j])));return points.map(p=>p.map((x,j)=>(x-(lo[j]+hi[j])/2)/Math.max(...hi.map((v,k)=>v-lo[k]))*10))}
 bind(){const c=this.canvas;c.addEventListener('pointerdown',e=>{c.setPointerCapture(e.pointerId);this.pointer.set(e.pointerId,[e.clientX,e.clientY]);this.dragged=false});c.addEventListener('pointermove',e=>{if(!this.pointer.has(e.pointerId))return;const old=this.pointer.get(e.pointerId),dx=e.clientX-old[0],dy=e.clientY-old[1];this.pointer.set(e.pointerId,[e.clientX,e.clientY]);if(Math.abs(dx)+Math.abs(dy)>2)this.dragged=true;if(this.pointer.size===2){this.zoom=Math.max(.4,Math.min(4,this.zoom+dy*.008));}else if(e.shiftKey){this.pan[0]+=dx;this.pan[1]+=dy}else{this.rotation[1]+=dx*.007;this.rotation[0]=Math.max(-1.5,Math.min(1.5,this.rotation[0]+dy*.007))}this.draw()});const end=e=>this.pointer.delete(e.pointerId);c.addEventListener('pointerup',end);c.addEventListener('pointercancel',end);c.addEventListener('wheel',e=>{e.preventDefault();this.zoom=Math.max(.4,Math.min(4,this.zoom*Math.exp(-e.deltaY*.001)));this.draw()},{passive:false});c.addEventListener('click',e=>{if(this.dragged)return;const r=c.getBoundingClientRect(),x=(e.clientX-r.left)*this.dpr,y=(e.clientY-r.top)*this.dpr;let best=-1,dist=19*this.dpr;for(const p of this.projected){if(!this.filtered.has(p.i))continue;const d=Math.hypot(x-p.x,y-p.y);if(d<dist){dist=d;best=p.i}}if(best>=0)this.onSelect(best)})}
 resize(){const r=this.canvas.getBoundingClientRect();this.dpr=Math.min(window.devicePixelRatio||1,2);this.canvas.width=Math.max(1,Math.round(r.width*this.dpr));this.canvas.height=Math.max(1,Math.round(r.height*this.dpr));this.draw()}
 setState(s){Object.assign(this,s);this.draw()}
 fit(){this.rotation=[-.18,.28];this.zoom=1;this.pan=[0,0];this.draw()}
 project(point){const [x,y,z]=point,[rx,ry]=this.rotation,cy=Math.cos(ry),sy=Math.sin(ry),cx=Math.cos(rx),sx=Math.sin(rx);const a=x*cy-z*sy,b=x*sy+z*cy;return [a,y*cx-b*sx,y*sx+b*cx]}
 draw(){const c=this.ctx,w=this.canvas.width,h=this.canvas.height;if(!w||!h)return;c.clearRect(0,0,w,h);const unit=Math.min(w,h)/13*this.zoom,centerX=w/2+this.pan[0]*this.dpr,centerY=h/2+this.pan[1]*this.dpr;this.projected=this.positions.map((p,i)=>{const [x,y,z]=this.project(p),pers=1/(1+z/27);return {i,x:centerX+x*unit*pers,y:centerY-y*unit*pers,z,pers}});const points=this.projected;
 c.strokeStyle='#57b8d819';c.lineWidth=this.dpr;for(let j=1;j<4;j++){c.beginPath();c.ellipse(centerX,centerY,unit*(1.7+j*.65),unit*(1.0+j*.4),this.rotation[1]*.2,0,Math.PI*2);c.stroke()}
 const highlight=new Set(this.path),related=new Set();if(this.connections){for(const [a,b] of this.edges)if(a===this.selected||b===this.selected)related.add(a),related.add(b)}
 if(this.connections||this.path.length>1){for(const [a,b,weight] of this.edges){if(!this.filtered.has(a)||!this.filtered.has(b))continue;const inPath=this.path.some((v,k)=>v===a&&this.path[k+1]===b);if(!inPath&&(!this.connections||a!==this.selected&&b!==this.selected))continue;const from=points[a],to=points[b];c.beginPath();c.moveTo(from.x,from.y);c.lineTo(to.x,to.y);c.strokeStyle=inPath?'#ffd57cdb':'#64dce034';c.lineWidth=(inPath?2.5:Math.min(1.7,.6+Math.log1p(weight)/9))*this.dpr;c.stroke()}}
 for(const p of [...points].sort((a,b)=>a.z-b.z)){const i=p.i;if(!this.filtered.has(i))continue;const n=this.neurons[i],selected=i===this.selected,hot=this.firing.has(i),active=this.active.has(i),silent=this.silent.has(i),onPath=highlight.has(i);const color=silent?'#fb849e':onPath?'#ffd77f':hot||active?'#70f3ef':n.region.startsWith('LO')||n.region.startsWith('ME')?'#93a5ff':'#6dbed5';const radius=(selected?5.7:hot?4.4:onPath?4.1:active?3.2:2.0)*p.pers*this.dpr;c.beginPath();c.fillStyle=color;c.globalAlpha=silent?.35:selected||hot||onPath?1:related.has(i)?.85:.57;c.shadowColor=color;c.shadowBlur=(selected||hot||onPath?20:active?12:3)*this.dpr;c.arc(p.x,p.y,radius,0,Math.PI*2);c.fill();if(selected){c.shadowBlur=0;c.strokeStyle='#ffffffa5';c.lineWidth=this.dpr;c.beginPath();c.arc(p.x,p.y,radius+5*this.dpr,0,Math.PI*2);c.stroke()}}
 c.globalAlpha=1;c.shadowBlur=0}
}
